[workspace]
members = [ "cli", "convert", "expression","parser", "scanner", "token"]
[workspace.dependencies]
token = { path = "./token" }
convert = { path = "./convert"}
log = { version = "0.4.22" }
